[package]
name = "zcash-android-wallet-sdk"
version = "0.0.1"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kevin Gorham <kevin.gorham@z.cash>",
]
description = "JNI backend for the Android wallet SDK"
publish = false
edition = "2018"

[dependencies]
android_logger = "0.6"
failure = "0.1"
futures = { version = "0.1", optional = true }
grpc = { version = "0.6", optional = true }
hex = "0.3"
jni = { version = "0.10", default-features = false }
log = "0.4"
log-panics = "2.0.0"

[dependencies.ff]
git = "https://github.com/str4d/librustzcash.git"
rev = "fe22862d3910f617ff58dfd0fff6fe6d60436db8"

[dependencies.pairing]
git = "https://github.com/str4d/librustzcash.git"
rev = "fe22862d3910f617ff58dfd0fff6fe6d60436db8"

[dependencies.sapling-crypto]
git = "https://github.com/str4d/librustzcash.git"
rev = "fe22862d3910f617ff58dfd0fff6fe6d60436db8"

[dependencies.zcash_client_backend]
git = "https://github.com/str4d/librustzcash.git"
rev = "fe22862d3910f617ff58dfd0fff6fe6d60436db8"
features = ["sqlite"]

[dependencies.zcash_primitives]
git = "https://github.com/str4d/librustzcash.git"
rev = "fe22862d3910f617ff58dfd0fff6fe6d60436db8"

[dependencies.zip32]
git = "https://github.com/str4d/librustzcash.git"
rev = "fe22862d3910f617ff58dfd0fff6fe6d60436db8"

[features]
updater = ["futures", "grpc"]

[lib]
name = "zcashwalletsdk"
path = "src/main/rust/lib.rs"
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "update-sapling-tree"
path = "src/main/rust/bin/update_sapling_tree.rs"
required-features = ["updater"]
